### ISSUE TITLE
Hey i cant sign up ..i am not receiving any code in my mail after i gave my mail there

### ISSUE THREAD

**Issue by Aruraka** [Akai771/AniMotion#2]

**Comment by Akai771** [comment]
Hello! Thank you for bringing it to my attention. Currently, the server's SMTP limit is three requests. If the limit is exceeded, the email verification code may not be delivered. Because this is a project and I am not covering server costs, there are limits to the number of emails sent. Thank you for your patience and understanding. Please try again later
